import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      { source: '/:path*', has: [{ type: 'host', value: 'hanatanigardenworks.com' }], destination: 'https://www.hanatanigardenworks.com/:path*', permanent: true },
      { source: '/posts/なぜ庭師仕事を取りに行くというブログを書くのか', destination: '/posts/post-12', permanent: true },
      { source: '/posts/ヴィジョンを決めたら行動に迷わなくなった', destination: '/posts/post-14', permanent: true },
      { source: '/posts/庭師仕事を取りに行くをどこで公開するか考えた', destination: '/posts/post-15', permanent: true },
      { source: '/posts/インスタグラムを始めました', destination: '/posts/post-16', permanent: true },
      { source: '/posts/名刺が完成したがまだ配れていない', destination: '/posts/post-17', permanent: true },
      { source: '/posts/フェンスの修理ついでにポスティング', destination: '/posts/post-18', permanent: true },
      { source: '/posts/庭師仕事を取りに行くブログの更新が届く仕組みを整えました', destination: '/posts/post-19', permanent: true },
      { source: '/posts/庭の完成形は見る人の心の中にある-南禅寺方丈庭園で学んだこと', destination: '/posts/post-20', permanent: true },
      { source: '/posts/庭は二度見ると深くなる', destination: '/posts/post-21', permanent: true },
      { source: '/posts/盆栽は作るより育てるほうが難しい', destination: '/posts/post-22', permanent: true },
      { source: '/posts/強剪定事例10mの高木を5mまで剪定屋根にかからない高さへ調整', destination: '/posts/post-23', permanent: true },
      { source: '/posts/リール16万再生youtubeショート7000再生強剪定動画の反応を記録', destination: '/posts/post-24', permanent: true },
      { source: '/posts/暇な時期にバイトではなく仕事を取りに行く準備を選びました', destination: '/posts/post-25', permanent: true },
      { source: '/posts/庭師は体の管理も仕事のうちです', destination: '/posts/post-27', permanent: true },
      { source: '/posts/造園業のdx化は進むでもなくならない仕事があります', destination: '/posts/post-28', permanent: true },
      { source: '/posts/植木屋は少ない仕事他の業種と比べて気づいたこと', destination: '/posts/post-29', permanent: true },
      { source: '/posts/その桜大丈夫ですか', destination: '/posts/post-30', permanent: true },
      { source: '/posts/仕事はこうやって広がっていくのかもしれません', destination: '/posts/post-31', permanent: true },
      { source: '/posts/仕事を取りに行く庭師1位になりました', destination: '/posts/post-32', permanent: true },
      { source: '/posts/盆栽の桜が咲きました旭山桜', destination: '/posts/post-33', permanent: true },
      { source: '/posts/横浜で花の博覧会ちょっと気になったので調べてみた', destination: '/posts/post-34', permanent: true },
      { source: '/posts/横浜花博テーマ展示ゾーンはどんな展示', destination: '/posts/post-35', permanent: true },
      { source: '/posts/ハナタニガーデンワークスについて', destination: '/posts/post-36', permanent: true },
      { source: '/posts/庭の手入れっていくら料金の目安をお伝えします', destination: '/posts/post-37', permanent: true },
      { source: '/posts/対応エリアはよくある質問にお答えします', destination: '/posts/post-38', permanent: true },
      { source: '/posts/横浜花博ガーデンパビリオンゾーンは一番参考になるかもしれない', destination: '/posts/post-39', permanent: true },
      { source: '/posts/妻が一番見たいと言ったゾーン自然共生エリアが一番リアルかもしれない', destination: '/posts/post-40', permanent: true },
      { source: '/posts/庭をキレイにしたら税金が6倍になる話', destination: '/posts/post-41', permanent: true },
      { source: '/posts/ホームページlpを作りました庭の考え方をまとめています', destination: '/posts/post-42', permanent: true },
      { source: '/posts/交流会で気づいたデザインの二極化と日本の美意識', destination: '/posts/post-43', permanent: true },
      { source: '/posts/初めてgoogle広告を出稿しましたやってみて感じたこと', destination: '/posts/post-44', permanent: true },
      { source: '/posts/年間管理って何をするのか庭のコンシェルジュの中身について', destination: '/posts/post-45', permanent: true },
      { source: '/posts/お問い合わせフォームの不具合を修正しました', destination: '/posts/post-46', permanent: true },
      { source: '/posts/気づいたらミモザが大きくなりすぎていませんか', destination: '/posts/post-47', permanent: true },
      { source: '/posts/google広告1週間後のリアルなデータを公開します', destination: '/posts/post-48', permanent: true },
      { source: '/posts/実は今が適期ユーカリの剪定放置していませんか', destination: '/posts/post-49', permanent: true },
      { source: '/posts/年1回お願いしてるのになぜかいつも気になる庭その理由わかりますか', destination: '/posts/post-50', permanent: true },
      { source: '/posts/気づいたらもさもさにシマトネリコの剪定今が1回目のタイミングです', destination: '/posts/post-51', permanent: true },
      { source: '/posts/防草シートを貼るなら知っておきたいプロが教えるリアルな話', destination: '/posts/post-52', permanent: true },
      { source: '/posts/緑化講習会に参加しましたみなさんの真剣な姿から気づいたこと', destination: '/posts/post-53', permanent: true },
      { source: '/posts/花が終わったら今すぐ動くツツジサツキの剪定タイミングがすべてです', destination: '/posts/post-54', permanent: true },
      { source: '/posts/1本だけでも頼んでいいのはいむしろ大歓迎です', destination: '/posts/post-55', permanent: true },
      { source: '/posts/街路樹に薬剤散布をしていますプロが教える目的と注意点', destination: '/posts/post-56', permanent: true },
      { source: '/posts/植木屋として独立して仕事を取るには王道と僕が選んだ別の道', destination: '/posts/post-57', permanent: true },
      { source: '/posts/木を切ったのにまた生えてくるもみじの伐採と切り株処理をプロが解説します', destination: '/posts/post-58', permanent: true },
      { source: '/posts/除草剤を注入した後次の木はいつ植えられる視聴者からの質問に答えます', destination: '/posts/post-59', permanent: true },
      { source: '/posts/除草剤グリホサートの疑問に答えます植物の中でどう働き枯れた後どうなるのか', destination: '/posts/post-60', permanent: true },
      { source: '/posts/補助金申請締め切り1時間前にgビズidが届いた話', destination: '/posts/post-61', permanent: true },
      { source: '/posts/319万再生されたらアンチコメントが来た', destination: '/posts/post-62', permanent: true },
      { source: '/posts/オリーブは暴れる木です美しい樹形を保つために剪定をする', destination: '/posts/post-63', permanent: true },
      { source: '/posts/抜根の費用はいくらかかる重機ありなしの実例を解説', destination: '/posts/post-64', permanent: true },
      { source: '/posts/桜の剪定中に白い巣を発見アメリカシロヒトリの恐怖', destination: '/posts/post-65', permanent: true },
      { source: '/posts/松のみどり摘み今が適期ですプロでもついやり過ぎてしまうその理由', destination: '/posts/post-66', permanent: true },
      { source: '/posts/google広告を1ヶ月運用した結果を正直に報告します', destination: '/posts/post-67', permanent: true },
      { source: '/posts/下地処理が雑だとこうなります防草シートの失敗例を報告します', destination: '/posts/post-68', permanent: true },
      { source: '/posts/剪定の時に意識していることプロが見ている不要枝の話', destination: '/posts/post-69', permanent: true },
      { source: '/posts/梅雨前にやっておきたい庭仕事除草と蜂の巣対策今がチャンスです', destination: '/posts/post-70', permanent: true },
    ];
  },
};

export default nextConfig;
